customhost = "employee.ca1wutqaonnv.ap-northeast-2.rds.amazonaws.com"
customuser = "kiranmysql"
custompass = "muboRlke1aticrid&atr"
customdb = "employee"
custombucket = "s3-addemployee"
customregion = "ap-northeast-2"
